
/**
	Do you see that pointing arrow that kindly aims to what you're selecting?
	Yeah that's a cursor.
*/

////////////////////////////////////////
// Getters from Cursor!
////////////////////////////////////////

function int getCursorRect(void){return comp_rects_once[STCOMP_CURSOR];}
function int getCursorWidth(void){return RectWidth(getCursorRect());}
function int getCursorHeight(void){return RectHeight(getCursorRect());}
function str getCursorIcon(void){return RectGetUserData(getCursorRect(), ST_CPROP2);}

///////////////////////////////////////
// Setters for teh Cursor!
///////////////////////////////////////

function void Cursor_setRect(int rect){comp_rects_once[STCOMP_CURSOR] = rect;}
function void Cursor_setIcon(str icon){SetRectUserData(getCursorRect(), ST_CPROP2, icon);}

///////////////////////////////////////
// Cursor functions!				 //
///////////////////////////////////////

function void Cursor_Initialize(int w, int h){
	int rect = RectCreate(CursorX(),CursorY(),w,h);
	Cursor_setRect(rect);
	Cursor_SetDefaultProps();
}

function void Cursor_SetDefaultProps (void){
	Cursor_setIcon("PNTR");
}

function void Cursor_UpdatePosition(void){
	Cursor_MoveToPoint(CursorX(), CursorY());
}

function void Cursor_MoveToRect(int rect){
	Cursor_MoveToPoint(
		RectX1(rect) + FixedDiv(RectWidth(rect), 2.0),
		RectY1(rect) + FixedDiv(RectHeight(rect), 2.0));
}

function void Cursor_MoveToPoint(int x, int y){
	UpdateCursor();
	setCursorPosition(x, y);
	setRectPosition(getCursorRect(), x, y);
}