///////////////////////////////////////////////////
//      SHOTGUN FRENZY
//   a mod by Wad'a'Holic

// f_Core.acs
#library "f_Core"

#import "f_Tip.acs"
#include "zcommon.acs"
#include "acsutils.acs"

script 122 (void)
{
	int countMe = 0;
	ambientsound("g/alarm", 64);
	while(countMe < 35){
		
		f_QuickBigCenterTipBold("BATTERY UNDER ATTACK!", cond(countMe % 2 == 0, CR_RED, CR_YELLOW));
		delay(5);
		countMe++;
	}
}