
#define BUILD_GENLAB 0
#define BUILD_ARMORY 1
#define BUILD_MARCOM 2
#define BUILD_REFINE 3
#define BUILD_MECHFA 4
#define BUILD_NUKESY 5


#define NOTBUILT 	0
#define BUILT 		1
#define LOCKED 		2


function bool isBuilt(int building){
	return c_BuildState[building] == BUILT;
}		

function bool isLocked(int building){
	return c_BuildState[building] == LOCKED;
}	

function void setBuildState(int building, int value)
{
	c_BuildState[building] = value;
}

