
#library "TEST"

#import "f_IntDB.acs"
#import "f_Tip.acs"

#import "f_FinalF.acs"
#import "f_PMen.acs"
#import "f_PHUD.acs"
#import "f_Rank.acs"
#import "f_Cred.acs"
#import "f_PStat.acs"
#import "f_StokP.acs"
//#import "f_TaticalMap.acs"

#include "zcommon.acs"
#include "samu_tools.acs"

#define List 100
str spawnerList[List];
int spawnselect = 0;
int spawnStack = 0;

script 100 Open{
	f_Gametype = 0;
	setupTerminals();
	f_Startcash =   2500;  
	
	addToSpawner("Annihilator");
	addToSpawner("ArchonOfHell");
	addToSpawner("BloodDemonClone");
	addToSpawner("Bloodfiend");
	addToSpawner("ChaingunGuy2");
	addToSpawner("ChainsawZombie");
	addToSpawner("Cyberbaron");
	addToSpawner("Cybruiser");
	addToSpawner("Hellion");
	addToSpawner("NailBorg");
	addToSpawner("NailBorgCommando");
	addToSpawner("NamiDarkImp");
	addToSpawner("sfArachnotron_tw");
	addToSpawner("sfArchvile");
	addToSpawner("sfBaronOfHell");
	addToSpawner("sfChaingunGuy");
	addToSpawner("sfCyberdemon");
	addToSpawner("sfDemon");
	addToSpawner("sfDoomImp");
	addToSpawner("sfFastZombie");
	addToSpawner("sfFatso");
	addToSpawner("sfHellKnight");
	addToSpawner("sfRevenant");
	addToSpawner("sfShotgunGuy");
	addToSpawner("sfZombieMan");
	addToSpawner("SlimeImp");
	addToSpawner("SpiderAnnihilator");
	addToSpawner("SSGZombie");
	addToSpawner("StoneDemon");
	addToSpawner("VoidDarkImp");
	
	SpawnSpot(spawnerList[spawnselect], 1,2,0);
	Thing_Deactivate(2);
}

script 10 (void){
	Thing_Activate(2);
}

script 12 (void){
	Thing_Remove(4);
	SpawnSpotFacing(spawnerList[spawnSelect], 3, 4);
	Thing_Hate(4,0,0);
}

script 11 (int dir){
	spawnselect += dir;
	if(spawnselect < 0) spawnselect = spawnstack-1;
	else if(spawnselect >= spawnstack) spawnselect = 0;
	Thing_Remove(2);
	SpawnSpot(spawnerList[spawnselect], 1,2,0);
	Thing_Deactivate(2);
	print(s:"Monster to spawn: ", s:spawnerList[spawnSelect]);
}

function void addToSpawner(str who){
	spawnerList[spawnStack] = who;
	spawnstack++;
}