///////////////////////////////////////////////////
//      SHOTGUN FRENZY
//   a mod by Wad'a'Holic

// f_MonAtt.acs
// monster attacking script

#library "f_MonAtt"
#include "zcommon.acs"

function void m_SpawnDemons (int l_Easy, int l_Med, int l_Hard)
{
    // spawn monsters
    if (l_Easy > 0)         thing_spawnnofog(115, l_Easy, 0, 110);
    if (l_Med > 0)          thing_spawnnofog(116, l_Med, 0, 110);
    if (l_Hard > 0)         thing_spawnnofog(117, l_Hard, 0, 110);
}  