#LibDefine	WP_SHOTGUN_W1D "\
\cdWeapon 1: Double Barreled Shotgun\n\
	\n\c-Accuracy: \cfC\
	\n\c-Power: \cfB\
	\n\c-Speed: \cfC\
	\n\c-N# Projectiles: \cf14 on fire / 7 on altfire\
	\n\c-Type: \cfHitscan\
	\n\c-Upgrade 1: \cfAutomatic load + blasting power.\
	\n\c-Upgrade 2: \cfIgnited Shells + more damage.\
"
#LibDefine WP_SHOTGUN_W2D "\
\cdWeapon 2: Chain-shell Quadshot\n\
	\n\c-Accuracy: \cfA\
	\n\c-Power: \cfB\
	\n\c-Speed: \cfD\
	\n\c-Proj Numb: \cf20\
	\n\c-Type: \cfHitscan\
	\n\c-Upgrade 1: \cfIgnited Shells + Bayonetta Chainsaw.\
	\n\c-Upgrade 2: \cfAutomated fire.\
"

#LibDefine WP_SHOTGUN_TITLE "Shotgun Weapon Pack"

#LibDefine WP_SHOTGUN_DESC "Standard set of weapons focused mainly on the shotguns."

#LibDefine WP_SHOTGUN_INFO "\
Recommended for privates who wishes to cause damage.\
\n\n\
\015 The \cfSSG \c-can shot \cf2 shells \c-at once. You know it.\
It is implemented the \cfSawed-off function\c-, so you can fire \cf1 shell at the time\c-.\
This little perk is useful to do a \cfcontrolated fire against the hordes of demons\c-.\
\n\n\
\015 The \cfQuadshot\c- is a powerful machine capable to fire \cf4 shells\c- at once!\
The only trade-off of this weapon, \cgit is slow on recharge\c-,\
but it's \cfaccuracy can assure you at least 3 or 4 kills per shot\c-."

// Assault Pack Strings.

#LibDefine	WP_ASSAULT_W1D "\
\cdWeapon 1: Assault Spitter Gun\n\
	\n\c-Accuracy: \cfC\
	\n\c-Power: \cfE\
	\n\c-Speed: \cfA\
	\n\c-N# Projectiles: \cf3\
	\n\c-Type: \cfHitscan\
	\n\c-Upgrade 1: \cfRest-less Fire + Toxic gas launcher.\
	\n\c-Upgrade 2: \cfBullet Spread + Shell fire.\
"
#LibDefine WP_ASSAULT_W2D "\
\cdWeapon 2: Semi-Automatic Buckshot\n\
	\n\c-Accuracy: \cfC\
	\n\c-Power: \cfB\
	\n\c-Speed: \cfC\
	\n\c-Proj Numb: \cf9\
	\n\c-Type: \cfHitscan\
	\n\c-Upgrade 1: \cfAutomatic fire + Chamber extend.\
	\n\c-Upgrade 2: \cfIgnited Shells + More damage.\
"

#LibDefine WP_ASSAULT_TITLE "Assault Weapon Pack"

#LibDefine WP_ASSAULT_DESC "Standard set of weapons designed for quick assault operations."

#LibDefine WP_ASSAULT_INFO "\
For fast assaults on the demons hordes.\
\n\n\
\015 It may be a pea-shotter, but \cfSpitter \c-is capable to keep control\
on the zombie crowd, just right \cfor their rushing waves\c-. Not to mention\
the nifty constant shot to \cfsnipe farer weak demons\c-.
\n\n\
\015 For stronger crowd, \cfBuckshot\c- will do the trick, It can be\
annoying to reload it. But the \cf10 shell burst\c- mitigates that little bug.\
To reload it, \cfuse your altfire\c-."

// Support Pack Strings.

#LibDefine	WP_SUPPORT_W1D "\
\cdTool 1: Supplier 8N4\n\
	\n\c-Fire: \cfAmmo\
	\n\c-AltFire: \cfHealth\
	\n\c-Type: \cfDispenser\
	\n\c-Upgrade 1: \cfMore drop of supplies.\
"

#LibDefine WP_SUPPORT_TITLE "Support Weapon Pack"

#LibDefine WP_SUPPORT_DESC "Set of tools to aid in the battle, without using the strength."

#LibDefine WP_SUPPORT_INFO "\
For the soldier who does'nt like to fight, but wants to aid their comrades.\
\n\n\
\015 The lack of health and ammo is stressful. Good thing the \cfSupplier\
exists.\n \cfFire to spawn ammo, and Altifire to spawn health\c-. Eazy."

// Heavy pack strings

#LibDefine	WP_HEAVY_W1D "\
\cdWeapon 1: Rocket Launcher\n\
	\n\c-Accuracy: \cfA\
	\n\c-Power: \cfB\
	\n\c-Speed: \cfB\
	\n\c-N# Projectiles: \cf1\
	\n\c-Type: \cfProjectile\
	\n\c-Upgrade 1: \cfExploding trail + more damage.\
	\n\c-Upgrade 2: \cfFast projectiles + more spread.\
"
#LibDefine WP_HEAVY_W2D "\
\cdWeapon 2: Flinger Grenade Launcher\n\
	\n\c-Accuracy: \cfB\
	\n\c-Power: \cfA\
	\n\c-Speed: \cfB\
	\n\c-Proj Numb: \cf1\
	\n\c-Type: \cfHitscan\
	\n\c-Upgrade 1: \cfCluster launcher + More spread.\
	\n\c-Upgrade 2: \cfToxic Gas + More Speed.\
"

#LibDefine WP_HEAVY_TITLE "Exploder Weapon Pack"

#LibDefine WP_HEAVY_DESC "Advanced set of weapons for explosive assaults."

#LibDefine WP_HEAVY_INFO "\
For strong marines.\
\n\n\
\015 The \cflauncher\c- is filled with the charged with 4KU Missiles\
designed for military warfare. You're gonna have lot'sa fun with this bad boy.\ 
Smite and ignite them with \cfexplosions straight to their feets!\c-.\
\n\n\
\015 The \cfflinger\c- is special in its kind, filled with a lot'sa of grenades.\
The grenades are designed to \cf-bounce arround\c- the place, aimed to the farer\
demons. A nifty alternate option \cfif you want to take cover\c-.\
."

// Plasma pack strings

#LibDefine	WP_PLASMA_W1D "\
\cdWeapon 1: Rocket Launcher\n\
	\n\c-Accuracy: \cfA\
	\n\c-Power: \cfB\
	\n\c-Speed: \cfB\
	\n\c-N# Projectiles: \cf1\
	\n\c-Type: \cfProjectile\
	\n\c-Upgrade 1: \cfExploding trail + more damage.\
	\n\c-Upgrade 2: \cfFast projectiles + more spread.\
"
#LibDefine WP_PLASMA_W2D "\
\cdWeapon 2: Flinger Grenade Launcher\n\
	\n\c-Accuracy: \cfB\
	\n\c-Power: \cfA\
	\n\c-Speed: \cfB\
	\n\c-Proj Numb: \cf1\
	\n\c-Type: \cfHitscan\
	\n\c-Upgrade 1: \cfCluster launcher + More spread.\
	\n\c-Upgrade 2: \cfToxic Gas + More Speed.\
"

#LibDefine WP_PLASMA_TITLE "Plasma Weapon Pack"

#LibDefine WP_PLASMA_DESC "Advanced set of weapons aimed to the technology."

#LibDefine WP_PLASMA_INFO "\
For strong marines.\
\n\n\
\015 The \cflauncher\c- is filled with the charged with 4KU Missiles\
designed for military warfare. You're gonna have lot'sa fun with this bad boy.\ 
Smite and ignite them with \cfexplosions straight to their feets!\c-.\
\n\n\
\015 The \cfflinger\c- is special in its kind, filled with a lot'sa of grenades.\
The grenades are designed to \cf-bounce arround\c- the place, aimed to the farer\
demons. A nifty alternate option \cfif you want to take cover\c-.\
."


#LibDefine	WP_COMANDO_W1D "\
\cdWeapon 1: Rocket Launcher\n\
	\n\c-Accuracy: \cfA\
	\n\c-Power: \cfB\
	\n\c-Speed: \cfB\
	\n\c-N# Projectiles: \cf1\
	\n\c-Type: \cfProjectile\
	\n\c-Upgrade 1: \cfExploding trail + more damage.\
	\n\c-Upgrade 2: \cfFast projectiles + more spread.\
"
#LibDefine WP_COMANDO_W2D "\
\cdWeapon 2: Flinger Grenade Launcher\n\
	\n\c-Accuracy: \cfB\
	\n\c-Power: \cfA\
	\n\c-Speed: \cfB\
	\n\c-Proj Numb: \cf1\
	\n\c-Type: \cfHitscan\
	\n\c-Upgrade 1: \cfCluster launcher + More spread.\
	\n\c-Upgrade 2: \cfToxic Gas + More Speed.\
"

#LibDefine WP_COMANDO_TITLE "Commando Weapon Pack"

#LibDefine WP_COMANDO_DESC "Advanced set of weapons designed to rip and tear hordes."

#LibDefine WP_COMANDO_INFO "\
For strong marines.\
\n\n\
\015 The \cflauncher\c- is filled with the charged with 4KU Missiles\
designed for military warfare. You're gonna have lot'sa fun with this bad boy.\ 
Smite and ignite them with \cfexplosions straight to their feets!\c-.\
\n\n\
\015 The \cfflinger\c- is special in its kind, filled with a lot'sa of grenades.\
The grenades are designed to \cf-bounce arround\c- the place, aimed to the farer\
demons. A nifty alternate option \cfif you want to take cover\c-.\
."

// Support Pack Strings.

#LibDefine	WP_BFG_W1D "\
\cdTool 1: Supplier 8N4\n\
	\n\c-Fire: \cfAmmo\
	\n\c-AltFire: \cfHealth\
	\n\c-Type: \cfDispenser\
	\n\c-Upgrade 1: \cfMore drop of supplies.\
"

#LibDefine WP_BFG_TITLE "Bio Force Gun Weapon Pack"

#LibDefine WP_BFG_DESC "Overpowered set of weapons designed to clean areas, at the old school."

#LibDefine WP_BFG_INFO "\
For the soldier who does'nt like to fight, but wants to aid their comrades.\
\n\n\
\015 The lack of health and ammo is stressful. Good thing the \cfSupplier\
exists.\n \cfFire to spawn ammo, and Altifire to spawn health\c-. Eazy."

// Support Pack Strings.

#LibDefine	WP_FLAMER_W1D "\
\cdTool 1: Supplier 8N4\n\
	\n\c-Fire: \cfAmmo\
	\n\c-AltFire: \cfHealth\
	\n\c-Type: \cfDispenser\
	\n\c-Upgrade 1: \cfMore drop of supplies.\
"

#LibDefine WP_FLAMER_TITLE "Pyromanicac Weapon Pack"

#LibDefine WP_FLAMER_DESC "Overpowered set of weapons to smite and ignite the demons."

#LibDefine WP_FLAMER_INFO "\
For the soldier who does'nt like to fight, but wants to aid their comrades.\
\n\n\
\015 The lack of health and ammo is stressful. Good thing the \cfSupplier\
exists.\n \cfFire to spawn ammo, and Altifire to spawn health\c-. Eazy."
